language: cpp
compiler:
  - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libeigen3-dev
 - git clone https://github.com/PetterS/spii.git spii
before_script:
  - mkdir build
  - cd build
  - cmake -DOPENMP=OFF -DSPII_INCLUDE=../spii/include .. 
script: 
  - make && ctest --output-on-failure
notifications:
  email:
    - ulen@maths.lth.se
    - petter.strandmark@gmail.com
